### ISSUE TITLE
Links to headings with emoji may be broken

### ISSUE THREAD

**Issue by LukeSavefrogs** [yzhang-gh/vscode-markdown#792]
#### What is the problem?
When an emoji is present in the heading, that heading will have the url broken because the extension will completely strip the emoji out of it, instead of including without the colon.
I could disable the `updateOnSave` feature and manually change the URLs, but that wouldn't prevent from erasing all my changes if i accidentally update it (since i'm used to it 😢).

#### How can I reproduce it?

1. Create a file with the following text:
```markdown
# :book: This won't work
# This won't work either :smile: 
# This will
```
2. Place the cursor at the start of the first line
3. Press <kbd>Ctrl</kbd> +<kbd>Shift</kbd> + <kbd>P</kbd>
4. Search for `Markdown All in One: Create Table of Contents` and click on it

As you can see the emojis are stripped out of the link, where they should be present but without the colon.

I created a [sample gist](https://gist.github.com/LukeSavefrogs/197f3ba1773ca3110b4c25118539a5cd) containing the lines i mentioned before.

#### Is there any error message in the console?

No

---

Thank you for your great work 😄 

Best Regards,
Luca

**Comment by Lemmingh** [comment]
Hi,

What's your `markdown.extension.toc.slugifyMode` setting?

It seems that `github` mode works as expected in version `3.2.0`.

**Comment by Lemmingh** [comment]
Emmm ... Even if I change the setting, I still cannot reproduce this.

![no-reproduce](https://user-images.githubusercontent.com/43396014/91158845-d3084080-e6f9-11ea-868a-b3dd03ed6d6f.png)

And I didn't find anything suspicious in the code.

https://github.com/yzhang-gh/vscode-markdown/blob/f822e721d0aba5d070c11128d201943e2891590d/src/util.ts#L114-L230
https://github.com/yzhang-gh/vscode-markdown/blob/f822e721d0aba5d070c11128d201943e2891590d/src/toc.ts#L339-L389
https://github.com/yzhang-gh/vscode-markdown/blob/f822e721d0aba5d070c11128d201943e2891590d/src/toc.ts#L188-L225

**Comment by yzhang-gh** [comment]
Thank you all for the information.

Here is the result on my PC

<img src="https://user-images.githubusercontent.com/7588612/91183984-b03c5300-e71e-11ea-9e6b-b38daae32504.png" width="499px">

So if you are using `:book:`, the link does contain a `book`.

Can you try again with other (Markdown) extensions disabled?

**Comment by chauff** [comment]
I have the same problem and played around with the different versions of the extension. Until version 2.8 the correct TOC links are generated but indeed from version 3 onwards the emojis are stripped out completely. For now my solution is to stick to version 2.8.

**Comment by Lemmingh** [comment]
If your "emoji" refers to "emoji character", such as `📖` (U+1F4D6), removing them is expected behavior. Because emoji characters falls into **Unicode General Category S**.

If your "emoji" refers to "emoji code", such as `:book:`, this might be a bug. Because a emoji code is just a sequence of ASCII characters, and ASCII letters and digits should be preserved.

**Comment by Lemmingh** [comment]
A notable change in version 3.0.0 is at `PUNCTUATION_REGEXP`:

https://github.com/yzhang-gh/vscode-markdown/commit/67fcde982a423dc990b5a5ccfba4f5f233a0ed56#diff-8cd4968b81985f0efc2053eabc37db6dR158

It's clear that **emoji characters** match this regexp and will be removed.

**Comment by yzhang-gh** [comment]
> A notable change in version 3.0.0 is at `PUNCTUATION_REGEXP`:
> 
> [67fcde9#diff-8cd4968b81985f0efc2053eabc37db6dR158](https://github.com/yzhang-gh/vscode-markdown/commit/67fcde982a423dc990b5a5ccfba4f5f233a0ed56#diff-8cd4968b81985f0efc2053eabc37db6dR158)
> 
> It's clear that **emoji characters** match this regexp and will be removed.

Interesting. Didn't really check that.

---

@chauff Can you elaborate on what is your expected output?
As shown in [this picture](https://github.com/yzhang-gh/vscode-markdown/issues/792#issuecomment-680047128), it looks to be working as expected (heading `# :book:` -> link `#book`, and `# 📖` -> `#`).
By saying "as expected", I mean GitHub generates the same links. (I'm using `slugifyMode: github`.)

**Comment by chauff** [comment]
Thanks for answering so quickly! With emojis I meant GitHub's recognized emoji code and yes, my `slugifyMode` is set to `github`.

This input:
```
# Section 1
...
## :bangbang: Subsection 1
...
## :orange_book: Subsection 2
...
```

yields the following TOC in version 2.8 and lower (this is the expected output):

```
- [Section 1](#section-1)
  - [:bangbang: Subsection 1](#bangbang-subsection-1)
  - [:orange_book: Subsection 2](#orangebook-subsection-2)
```

However, in version 3+, the TOC looks as follows (the emoji code is no longer converted, but simply removed): 

```
- [Section 1](#section-1)
  - [:bangbang: Subsection 1](#️-subsection-1)
  - [:orange_book: Subsection 2](#-subsection-2)
```

**Comment by Lemmingh** [comment]
Then, are you also using other extensions like [Markdown Emoji](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-emoji)?

**Comment by yzhang-gh** [comment]
It is related to the Markdown Emoji extension.

I don't use that extension so the output on my PC is

```
- [Section 1](#section-1)
  - [:bangbang: Subsection 1](#bangbang-subsection-1)
  - [:orange_book: Subsection 2](#orange_book-subsection-2)
```

After I install that extension, it becomes

```
- [Section 1](#section-1)
  - [:bangbang: Subsection 1](#️-subsection-1)
  - [:orange_book: Subsection 2](#-subsection-2)
```

**Comment by Lemmingh** [comment]
The solution is pretty tricky.

VS Code and GitHub diverge greatly on heading ID generation logic.

To generate TOC links that work in VS Code's built-in preview, you have to set `slugifyMode` to `vscode`.

See
#807
microsoft/vscode#106296

---

I'm afraid there is few thing to do with this extension.

https://github.com/yzhang-gh/vscode-markdown/blob/a4cea4dee6ea9caec977f66f741ffe1e683af8fe/CHANGELOG.md#L65

**Comment by Lemmingh** [comment]
Wait, sorry, I missed a point.

We may need to handle this:

https://github.com/yzhang-gh/vscode-markdown/blob/64ca3472de9251cff7052764299eccefb2e95285/src/util.ts#L131-L132

**Comment by yzhang-gh** [comment]
> We may need to handle this:
> 
> https://github.com/yzhang-gh/vscode-markdown/blob/64ca3472de9251cff7052764299eccefb2e95285/src/util.ts#L131-L132

@Lemmingh You are right. We cannot use the same MarkdownEngine (i.e. `mdEngine.cacheMd`) which is used for rendering. We intended to remove Markdown syntaxes (bold, italic etc.) but it turns out that Emojis are also removed.

**Comment by Lemmingh** [comment]
It's a relatively big bug. Major features, including TOC generation, printing, and code completion, rely on `slugify()`, thus, are affected.

I've refactored `mdHeadingToPlaintext()` on branch `slugify`. Then, we can implement a CommonMark-compliant (assuming the input string is in pure CommonMark) method first.

If someday someone requests support for a platform whose "Markdown to plain text conversion" method is different, we can simply append the new method there.

**Comment by yzhang-gh** [comment]
I've pushed a temporary fix for this issue. It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

**Comment by Lemmingh** [comment]
🎉 b5b9ebfc64b2863fc252f79eaeb6af32e7ca5769 should fix the **link generation** of **GitHub** and **GitLab** mode. Please check its dev build:
https://github.com/yzhang-gh/vscode-markdown/actions/runs/257866190

## ⚠ Known issues

1. "Printing" may not generate correct heading ID.

   Failed cases:

   ```markdown
   ## `<em>code</em>`
   ## :sweat_smile:
   ```

2. Some headings may lead to weird TOC text. Links are not affected.

   For example:

   ```markdown
   ## a][b
   ## image ![moz](https://www.mozilla.org/media/protocol/img/logos/mozilla/black.40d1af88c248.svg) logo
   ```

Thank you.

**Comment by LukeSavefrogs** [comment]
When will reach the VSCode Marketplace?

**Comment by yzhang-gh** [comment]
Already in v3.4.0

**Comment by sanmai-NL** [comment]
@yzhang-gh For us, this generated anchor still doesn't work inside VS Code and with mdBook.

```markdown
# Test

- [Test](#test)
  - [👷🏼‍♀️ Opdracht](#️-opdracht)

## 👷🏼‍♀️ Opdracht
```

How can this be solved?

**Comment by Lemmingh** [comment]
@sanmai-NL

What's your Slugify Mode (`markdown.extension.toc.slugifyMode`)?

The default `github` (GitHub) is **not compatible** with `vscode` (Visual Studio Code).

---

The **original issue** was to solve a conflict with [`markdown-it-emoji`](https://www.npmjs.com/package/markdown-it-emoji).

https://github.com/yzhang-gh/vscode-markdown/issues/792#issuecomment-689275280
https://github.com/yzhang-gh/vscode-markdown/issues/792#issuecomment-688859776

**Comment by sanmai-NL** [comment]
@Lemmingh My slugify mode is `github`. I was aware of that :). I don’t know why I mentioned VS Code then. The issue that motivated me to chime in was the [mdBook](https://github.com/rust-lang/mdBook) incompatibility.

**Comment by Lemmingh** [comment]
This file appears to be responsible for generating anchor ID in mdBook:

https://docs.rs/mdbook/0.4.4/src/mdbook/renderer/html_handlebars/hbs_renderer.rs.html#742

Please open a new **feature request** for **adding slugify support for mdBook**.

---

However, I'm afraid we're not familiar with Rust, thus, will have to **wait for help from community**.

Thank you.
